import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

# [shell]
# program = "/usr/bin/zsh"

[env]
term = "alacritty"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
size = 16

[window]
# opacity = 0.85
# blur = true
decorations = "None"
dynamic_padding = true

[bell]
# animation = "Linear"
# duration = 50
animation = "EaseOutExpo"
duration = 300
color = "#1e1e2e"

